version: 2.1
jobs:
  build-gcc:
    docker:
      - image: mpsm/spyc-builder
    steps:
      - checkout
      - run: "make -j -r -R CXX=g++ app"

  build-clang:
    docker:
      - image: mpsm/spyc-builder
    steps:
      - checkout
      - run: "make -j -r -R CXX=${CLANG_SYSROOT}/bin/clang++ app"

  build-tests:
    docker:
      - image: mpsm/spyc-builder
    steps:
      - checkout
      - run: "make -j -r -R CXX=g++ testapp"
      - persist_to_workspace:
          root: build
          paths:
            - test
            - testall

  test:
    docker:
      - image: mpsm/spyc-builder
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: "find build | xargs touch"
      - run:
          name: "Running tests"
          command: "./build/testall --gtest_output=xml"
      - run: "mkdir -p test-results/gtest && mv test_detail.xml test-results/gtest/"
      - store_test_results:
          path: test-results
      - run:
          name: "Uploading coverage report"
          command: "gcov -r -o build/test src/* test/*; curl -s https://codecov.io/bash | bash -s -- -X gcov -t ${CODECOV_TOKEN} -n ${CIRCLE_BUILD_NUM} -Z || echo \"Codecov upload failed\""
          when: always

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-gcc
      - build-clang
      - build-tests
      - test:
          requires:
            - build-tests
